### ISSUE TITLE
How to override the on save?

### ISSUE THREAD

**Issue by captmomo** [DevExpress-Examples/Dashboard-for-ASP.NET-Core-How-to-save-dashboards-to-a-database#2]
Hi
How do I override the on save to pass in additional parameters?
And How do I use this with EFCore?

**Comment by Stason4eg** [comment]
Hello,

Thank you for your inquiry. I invite you to create a new support ticket regarding this question in our Support Center: devexpress.com/ask. 
Our Support Center is the main channel where we process all technical inquiries. Our Support Team will follow up with you in your SC ticket.
